name: exercicetest

on: 
  push:
  workflow_dispatch:  

jobs:
  postman-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Installer newman
        run: npm install -g newman

      - name: executer la collection postman
        run: newman run collection.json
        
      - name: newman run notre collection
        run: newman run collection.json --reporters=cli,htmlextra
